// Generated by gencpp from file ros_msg/msgData.msg
// DO NOT EDIT!


#ifndef ROS_MSG_MESSAGE_MSGDATA_H
#define ROS_MSG_MESSAGE_MSGDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_msg
{
template <class ContainerAllocator>
struct msgData_
{
  typedef msgData_<ContainerAllocator> Type;

  msgData_()
    : Join_data()
    , Join_state()
    , data(0)  {
      Join_data.assign(0.0);

      Join_state.assign(0.0);
  }
  msgData_(const ContainerAllocator& _alloc)
    : Join_data()
    , Join_state()
    , data(0)  {
  (void)_alloc;
      Join_data.assign(0.0);

      Join_state.assign(0.0);
  }



   typedef boost::array<double, 6>  _Join_data_type;
  _Join_data_type Join_data;

   typedef boost::array<double, 6>  _Join_state_type;
  _Join_state_type Join_state;

   typedef uint32_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::ros_msg::msgData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_msg::msgData_<ContainerAllocator> const> ConstPtr;

}; // struct msgData_

typedef ::ros_msg::msgData_<std::allocator<void> > msgData;

typedef boost::shared_ptr< ::ros_msg::msgData > msgDataPtr;
typedef boost::shared_ptr< ::ros_msg::msgData const> msgDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_msg::msgData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_msg::msgData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_msg::msgData_<ContainerAllocator1> & lhs, const ::ros_msg::msgData_<ContainerAllocator2> & rhs)
{
  return lhs.Join_data == rhs.Join_data &&
    lhs.Join_state == rhs.Join_state &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_msg::msgData_<ContainerAllocator1> & lhs, const ::ros_msg::msgData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_msg::msgData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_msg::msgData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_msg::msgData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_msg::msgData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_msg::msgData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_msg::msgData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_msg::msgData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73f187edf478e820d25171010c16a164";
  }

  static const char* value(const ::ros_msg::msgData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73f187edf478e820ULL;
  static const uint64_t static_value2 = 0xd25171010c16a164ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_msg::msgData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_msg/msgData";
  }

  static const char* value(const ::ros_msg::msgData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_msg::msgData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[6] Join_data\n"
"float64[6] Join_state\n"
"uint32 data\n"
;
  }

  static const char* value(const ::ros_msg::msgData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_msg::msgData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Join_data);
      stream.next(m.Join_state);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct msgData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_msg::msgData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_msg::msgData_<ContainerAllocator>& v)
  {
    s << indent << "Join_data[]" << std::endl;
    for (size_t i = 0; i < v.Join_data.size(); ++i)
    {
      s << indent << "  Join_data[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.Join_data[i]);
    }
    s << indent << "Join_state[]" << std::endl;
    for (size_t i = 0; i < v.Join_state.size(); ++i)
    {
      s << indent << "  Join_state[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.Join_state[i]);
    }
    s << indent << "data: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_MSG_MESSAGE_MSGDATA_H
